### ISSUE TITLE
Suggestion to rename .whitespaces to .whitespace or .whitespaceOrTab or to change their behaviour

### ISSUE THREAD

**Issue by explicitcall** [SwiftStudies/OysterKit#55]
When reviewing #47 I realised that `.whitespaces` naming doesn't play well with `.whitespaces*`, `.whitespaces+` or `.whitespace?`. It implies that many whitespaces may be matched, while only one is matched.

It could be better for library user experience to either rename it or make it match multiple symbols.
Possible naming: `.whitespace`, `.whitespaceChar`, `.whitespaceCharacter`, `.whitespaceOrTab`.

Same actually could be applied to `.newlines`, which I think matches only one newline character.

Overall, looking at character sets, singular/plural naming is inconsistent at a first glance. I understand that it applies to the number of characters in a character set, but users of STLR might not understand it this way (like it happened to me). I think that communicating how many characters will be matched is more important than how many characters are in a set.

**Comment by SwiftStudies** [comment]
You are not the first to make this proposal and I think at this point although my goal was to be consistent with Swift... Good affordance is more important. I'll prepare a branch with this change in next week.
