### ISSUE TITLE
OysterKit.swift missing

### ISSUE THREAD

**Issue by KiGi** [SwiftStudies/OysterKit#6]
I converted the code to use Swift 1.2, and also fixed the absolute path in the project to get things compiling.

One thing I'm not sure I can work around though, the iOS version of the OysterKit framework includes the file "OysterKit.swift", which is not in the project anywhere.  I note that the Mac version of the framework has OKStandard.swift - is that a new name for the same file?

**Comment by KiGi** [comment]
On further examination of the project structure it looked like that is exactly what happened - I deleted the framework folder from the iOS Framework, then re-added it.  That also cleared up the absolute path issue mentioned in another issue.  I'll get a pull request put up when I get the whole thing tested a bit.

**Comment by SwiftStudies** [comment]
That would be excellent. Thank you for doing this. I'll pick up the pull when you have it.

**Comment by KiGi** [comment]
I'm going to send up the pull request today, but I have a warning - the Mac demo doesn't seem to work any more.  The tokenizer never gives back any tokens regardless of the input string,.. if you wanted to try to fix that it would be great, otherwise I'll probably look at that over the next few days.  I just wanted to warn you not to just merge it into the public facing code as-is...
