### ISSUE TITLE
pinned terms as regex

### ISSUE THREAD

**Issue by wess** [SwiftStudies/OysterKit#67]
Make pinned terms able to be regex like traditional lexers

**Comment by SwiftStudies** [comment]
The only thing that's made my shy away from RegEx so far is that there is a vision for Swift native RegEx support in the future, and a "fear of reimplementing". I would be interested in your thoughts. 

Secondly... why only pinned terms?

**Comment by wess** [comment]
I would love to use this for writing a programming language, your example for Bork is nice, and I love the syntax, but it's a little harder to follow if I want to use this for a programming language

**Comment by SwiftStudies** [comment]
I've merged this into the mater branch. Seems to work well and it was a great enhancement

**Comment by wess** [comment]
You can ping me on telegram, or twitter. My usernames on both are @wesscope
