### ISSUE TITLE
Offer a brew install option for command line tool

### ISSUE THREAD

**Issue by wess** [SwiftStudies/OysterKit#80]
Following how Swiftenv (https://swiftenv.fuller.li/en/latest/installation.html) does the brew install setup, I would love to be able to install the command line interface via brew instead of having to worry about cloning or using it on some variance of a path.

**Comment by SwiftStudies** [comment]
Sounds good... I'm going to tag this for version 1.0. 

In the mean time you can install it by running

    swift run stlrc install

Just like home-brew this will install it in ```/usr/local/bin``` and you can subsequently run with just ```stlrc``` and won't have to do anything with your path
